[workspace]

members = [
    "relay",
    "relay-core",
    "relay-frontend-http",
    "relay-backend-postgres",
]

[workspace.package]
edition = "2021"
authors = ["Dean Karn"]
description = "A no nonsense, horizontally scalable, ordered job runner backed by Postgres"

[workspace.dependencies]
clap = "4"
tokio = { version = "1.28.2", default-features =  false }
anyhow = "1.0.71"
thiserror = "1.0.40"
serde = { version = "1.0.163" }
serde_json = { version = "1.0.96" }
tracing = "0.1.37"
uuid = { version = "1.3.3" }
chrono = "0.4.26"
backoff-rs = "0.1.0"
reqwest = { version = "0.11.18" }
metrics = "0.21.0"
percent-encoding = "2.2.0"
async-channel = "1.8.0"
async-trait = "0.1.68"
anydate = "0.3.0"
metrics-util = "0.15.0"
log = "0.4.18"
relay-core = { version = "*", path="./relay-core" }

[profile.release]
lto = true
strip = true
codegen-units = 1
