[workspace]

members = [
    "relay",
    "relay-core",
    "relay-frontend-http",
    "relay-backend-postgres",
]

[workspace.package]
edition = "2021"
authors = ["Dean Karn"]
description = "A no nonsense, horizontally scalable, ordered job runner backed by Postgres"

[workspace.dependencies]
clap = "4"
tokio = { version = "1.23.0", default-features =  false }
anyhow = "1.0.66"
thiserror = "1.0.37"
serde = { version = "1.0.151" }
serde_json = { version = "1.0.89" }
tracing = "0.1.37"
uuid = { version = "1.2.2" }
chrono = "0.4.23"
backoff-rs = "0.1.0"
reqwest = { version = "0.11.13" }
metrics = "0.20.1"
percent-encoding = "2.2.0"
async-channel = "1.8.0"
async-trait = "0.1.59"
anydate = "0.3.0"
metrics-util = "0.14.0"
log = "0.4.17"
relay-core = { version = "*", path="./relay-core" }

[profile.release]
lto = true
strip = true
codegen-units = 1
