version: "3.7"
services:
  postgres:
    image: postgres:9.6.12
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: username
      POSTGRES_PASS: pass
      POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: trust

  postgres2:
    image: postgres:9.6.12
    ports:
      - "5433:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: username
      POSTGRES_PASS: pass
      POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: trust