version: "3.7"
services:
  postgres:
    image: postgres:9.6.12
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: username
      POSTGRES_PASS: pass
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_MULTIPLE_DATABASES: relay,scheduler