[package]
name = "relay-frontend-http"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relay-core = { version = "0.3", path="../relay-core" }
tracing = "0.1.37"
actix-web = { version = "4.2.1", default-features = false, features = ["compress-gzip", "rustls"] }
metrics = "0.20.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = { version = "1.0.87", features = ["raw_value"] }
anyhow = "1.0.66"
