[package]
name = "relay-frontend-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relay-core = { version = "0.1", path="../relay-core" }
tracing = "0.1.34"
actix-web = { version = "4.0.1", default-features = false, features = ["compress-gzip", "rustls"] }
metrics = "0.18.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["raw_value"] }
anyhow = "1.0.58"
