[package]
name = "relay"
version = "0.5.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.17", features = ["derive", "env"] }
tokio = { version = "1.18.1", features = ["rt-multi-thread", "net", "time","macros"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
metrics-exporter-prometheus = { version = "0.9.0", optional = true }
metrics-util = "0.12.1"
metrics = "0.18.1"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["raw_value"] }
log = "0.4.17"
tracing = "0.1.34"
sqlx = { version = "0.5.13", features = ["postgres", "chrono","runtime-tokio-rustls", "all-types", "migrate"] }
actix-web = { version = "4.0.1", default-features = false, features = ["compress-gzip", "rustls"] }
thiserror = "1.0.31"
anydate = { version = "0.3.0", features = ["serde"] }

[dev-dependencies]
uuid = { version = "1.0.0", features = ["v4"] }

[features]
default = []
metrics-prometheus = ["metrics-exporter-prometheus"]
