[package]
name = "relay"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.14", features = ["derive", "env"] }
tokio = { version = "1.18.0", features = ["rt-multi-thread", "net", "time","macros"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
metrics-exporter-prometheus = { version = "0.9.0", optional = true }
metrics-util = "0.12.0"
metrics = "0.18.1"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.80", features = ["raw_value"] }
log = "0.4.16"
tracing = "0.1.34"
actix-web = { version = "4.0.1", default-features = false, features = ["compress-gzip", "rustls"] }
thiserror = "1.0.31"
anydate = { version = "0.3.0", features = ["serde"] }
tokio-postgres = {version = "0.7.6", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"]}
deadpool-postgres = "0.10.2"
refinery = {version = "0.8.4", features = ["tokio-postgres"]}

[features]
default = []
metrics-prometheus = ["metrics-exporter-prometheus"]
