version: "3.7"
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: relay
      POSTGRES_USER: username
      POSTGRES_PASS: pass
      POSTGRES_HOST_AUTH_METHOD: trust