[package]
name = "relay-backend-postgres"
version = "0.4.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relay-core.workspace = true
sqlx = { version = "0.6.2", features = ["postgres", "chrono","runtime-tokio-rustls", "all-types", "migrate"] }
log.workspace = true
tracing.workspace = true
metrics.workspace = true
chrono.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
async-trait.workspace = true

[dev-dependencies]
uuid = { workspace = true, features = ["v4"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "net", "time","macros"] }
