[package]
name = "relay-backend-postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relay-core = { version = "0.1", path="../relay-core" }
sqlx = { version = "0.5.13", features = ["postgres", "chrono","runtime-tokio-rustls", "all-types", "migrate"] }
log = "0.4.17"
tracing = "0.1.34"
metrics = "0.18.1"
chrono = "0.4.19"
serde_json = { version = "1.0.81", features = ["raw_value"] }
async-trait = "0.1.56"

[dev-dependencies]
uuid = { version = "1.0.0", features = ["v4"] }
anyhow = "1.0.57"
tokio = { version = "1.18.2", features = ["rt-multi-thread", "net", "time","macros"] }
