name: Lint & Test
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
#        volumes:
#          - ${{ github.workspace }}/schema:/docker-entrypoint-initdb.d
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: username
          POSTGRES_PASS: pass
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: relay
#          POSTGRES_MULTIPLE_DATABASES: relay
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.platform }}-v1
      - run: DATABASE_URL="postgres://username:pass@localhost:5432/relay?sslmode=disable" cargo test --all-features --all-targets

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.platform }}-v1
      - run: cargo check --all-features --all-targets

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - uses: Swatinem/rust-cache@v1
        with:
          key: ubuntu-latest-v1
      - run: cargo clippy --all-features --tests -- -Dclippy::all -Dclippy::pedantic
