[package]
name = "relay-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.31"
serde = { version = "1.0.138", features = ["derive"] }
anydate = { version = "0.3.0", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
async-trait = "0.1.56"
